### ISSUE TITLE
Rails 7 can't modify frozen Array

### ISSUE THREAD

**Issue by DevHachi** [NachoPal/dry_i18n#5]
We are currently upgrading from rails 6.1.0 to rails 7.0.4 and discovered this error.

FrozenError: can't modify frozen Array: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
from .../gems/dry_i18n-1.0.1/lib/dry_i18n.rb:13:in `block in translate'

This happens for I18n.t('date.abbr_day_names') and for I18n.l(DateTime.current, format: '%B %Y')

Here is the yml file, to reproduce the error.

```
en:
  date:
    abbr_day_names:
    - Sun
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
```
